/** Crunchbase industry groups + industries used for investor sector search. */
export type CrunchbaseIndustry = {
  name: string;
  group: string;
};

export const CRUNCHBASE_INDUSTRY_GROUPS = [
  "Administrative Services",
  "Advertising",
  "Agriculture and Farming",
  "Apps",
  "Artificial Intelligence",
  "Biotechnology",
  "Clothing and Apparel",
  "Commerce and Shopping",
  "Community and Lifestyle",
  "Consumer Electronics",
  "Consumer Goods",
  "Content and Publishing",
  "Data and Analytics",
  "Design",
  "Education",
  "Energy",
  "Events",
  "Financial Services",
  "Food and Beverage",
  "Gaming",
  "Government and Military",
  "Hardware",
  "Health Care",
  "Information Technology",
  "Internet Services",
  "Lending and Investments",
  "Manufacturing",
  "Media and Entertainment",
  "Messaging and Telecommunications",
  "Mobile",
  "Music and Audio",
  "Natural Resources",
  "Navigation and Mapping",
  "Payments",
  "Platforms",
  "Privacy and Security",
  "Professional Services",
  "Real Estate",
  "Sales and Marketing",
  "Science and Engineering",
  "Software",
  "Sports",
  "Sustainability",
  "Transportation",
  "Travel and Tourism",
  "Video",
] as const;

const CRUNCHBASE_INDUSTRY_ROWS: Array<[name: string, group: string]> = [
  ["3D Printing", "Hardware"],
  ["3D Technology", "Hardware"],
  ["Accounting", "Financial Services"],
  ["Ad Network", "Advertising"],
  ["Ad Retargeting", "Advertising"],
  ["Advanced Materials", "Science and Engineering"],
  ["Aerospace", "Science and Engineering"],
  ["Affiliate Marketing", "Sales and Marketing"],
  ["AgTech", "Agriculture and Farming"],
  ["Agriculture", "Agriculture and Farming"],
  ["Analytics", "Data and Analytics"],
  ["Angel Investment", "Lending and Investments"],
  ["Animation", "Media and Entertainment"],
  ["App Discovery", "Apps"],
  ["Application Performance Management", "Software"],
  ["Apps", "Apps"],
  ["Architecture", "Design"],
  ["Artificial Intelligence", "Artificial Intelligence"],
  ["Asset Management", "Financial Services"],
  ["Audio", "Music and Audio"],
  ["Augmented Reality", "Hardware"],
  ["Auto Insurance", "Financial Services"],
  ["Automotive", "Transportation"],
  ["Autonomous Vehicles", "Transportation"],
  ["B2B", "Software"],
  ["B2C", "Commerce and Shopping"],
  ["Banking", "Financial Services"],
  ["Battery", "Energy"],
  ["Beauty", "Consumer Goods"],
  ["Big Data", "Data and Analytics"],
  ["Billing", "Financial Services"],
  ["Bioinformatics", "Biotechnology"],
  ["Biometrics", "Privacy and Security"],
  ["Biotechnology", "Biotechnology"],
  ["Bitcoin", "Financial Services"],
  ["Brand Marketing", "Sales and Marketing"],
  ["Broadcasting", "Media and Entertainment"],
  ["Building Material", "Manufacturing"],
  ["Business Development", "Professional Services"],
  ["Business Intelligence", "Data and Analytics"],
  ["Business Process Automation", "Software"],
  ["CAD", "Software"],
  ["Call Center", "Administrative Services"],
  ["Cannabis", "Health Care"],
  ["Car Sharing", "Transportation"],
  ["Career Planning", "Professional Services"],
  ["Casual Games", "Gaming"],
  ["Chemical", "Manufacturing"],
  ["Chemical Engineering", "Science and Engineering"],
  ["Child Care", "Community and Lifestyle"],
  ["Civil Engineering", "Science and Engineering"],
  ["Classifieds", "Commerce and Shopping"],
  ["Clean Energy", "Energy"],
  ["CleanTech", "Sustainability"],
  ["Clinical Trials", "Health Care"],
  ["Cloud Computing", "Information Technology"],
  ["Cloud Data Services", "Data and Analytics"],
  ["Cloud Infrastructure", "Information Technology"],
  ["Cloud Management", "Information Technology"],
  ["Cloud Security", "Privacy and Security"],
  ["Cloud Storage", "Information Technology"],
  ["CMS", "Software"],
  ["Collaboration", "Software"],
  ["Collections", "Financial Services"],
  ["College Recruiting", "Education"],
  ["Commercial Insurance", "Financial Services"],
  ["Commercial Lending", "Lending and Investments"],
  ["Commercial Real Estate", "Real Estate"],
  ["Communications Infrastructure", "Messaging and Telecommunications"],
  ["Communities", "Community and Lifestyle"],
  ["Compliance", "Professional Services"],
  ["Computer Vision", "Artificial Intelligence"],
  ["Concerts", "Events"],
  ["Console Games", "Gaming"],
  ["Construction", "Real Estate"],
  ["Consulting", "Professional Services"],
  ["Consumer Applications", "Apps"],
  ["Consumer Electronics", "Consumer Electronics"],
  ["Consumer Goods", "Consumer Goods"],
  ["Consumer Lending", "Lending and Investments"],
  ["Consumer Research", "Sales and Marketing"],
  ["Consumer Software", "Software"],
  ["Contact Management", "Sales and Marketing"],
  ["Content", "Content and Publishing"],
  ["Content Delivery Network", "Internet Services"],
  ["Content Discovery", "Content and Publishing"],
  ["Content Marketing", "Sales and Marketing"],
  ["Continuing Education", "Education"],
  ["Corporate Training", "Education"],
  ["Cosmetics", "Consumer Goods"],
  ["Courier Service", "Transportation"],
  ["Coworking", "Real Estate"],
  ["Creative Agency", "Advertising"],
  ["Credit", "Financial Services"],
  ["Credit Cards", "Payments"],
  ["CRM", "Sales and Marketing"],
  ["Crowdfunding", "Lending and Investments"],
  ["Crowdsourcing", "Internet Services"],
  ["Cryptocurrency", "Financial Services"],
  ["Customer Service", "Professional Services"],
  ["Cyber Security", "Privacy and Security"],
  ["Data Center", "Information Technology"],
  ["Data Integration", "Data and Analytics"],
  ["Data Mining", "Data and Analytics"],
  ["Data Visualization", "Data and Analytics"],
  ["Database", "Data and Analytics"],
  ["Dating", "Community and Lifestyle"],
  ["Delivery", "Transportation"],
  ["Delivery Service", "Transportation"],
  ["Dental", "Health Care"],
  ["Developer APIs", "Software"],
  ["Developer Platform", "Software"],
  ["Developer Tools", "Software"],
  ["Diabetes", "Health Care"],
  ["Digital Entertainment", "Media and Entertainment"],
  ["Digital Marketing", "Sales and Marketing"],
  ["Digital Media", "Media and Entertainment"],
  ["Direct Marketing", "Sales and Marketing"],
  ["Document Management", "Software"],
  ["Domain Registrar", "Internet Services"],
  ["Drones", "Hardware"],
  ["E-Commerce", "Commerce and Shopping"],
  ["E-Commerce Platforms", "Commerce and Shopping"],
  ["E-Learning", "Education"],
  ["E-Signature", "Software"],
  ["EdTech", "Education"],
  ["Education", "Education"],
  ["Elder Care", "Health Care"],
  ["Electric Vehicle", "Transportation"],
  ["Electronics", "Hardware"],
  ["Email", "Internet Services"],
  ["Email Marketing", "Sales and Marketing"],
  ["Embedded Software", "Software"],
  ["Embedded Systems", "Hardware"],
  ["Emergency Medicine", "Health Care"],
  ["Employee Benefits", "Professional Services"],
  ["Employment", "Professional Services"],
  ["Energy", "Energy"],
  ["Energy Efficiency", "Energy"],
  ["Energy Management", "Energy"],
  ["Energy Storage", "Energy"],
  ["Enterprise Applications", "Software"],
  ["Enterprise Resource Planning (ERP)", "Software"],
  ["Enterprise Software", "Software"],
  ["Environmental Engineering", "Science and Engineering"],
  ["ESports", "Gaming"],
  ["Event Management", "Events"],
  ["Events", "Events"],
  ["Facial Recognition", "Artificial Intelligence"],
  ["Family", "Community and Lifestyle"],
  ["Fantasy Sports", "Sports"],
  ["Farming", "Agriculture and Farming"],
  ["Fashion", "Clothing and Apparel"],
  ["Fast-Moving Consumer Goods", "Consumer Goods"],
  ["Fertility", "Health Care"],
  ["Field Support", "Professional Services"],
  ["Film", "Media and Entertainment"],
  ["Film Production", "Media and Entertainment"],
  ["FinTech", "Financial Services"],
  ["Finance", "Financial Services"],
  ["Financial Exchanges", "Financial Services"],
  ["Financial Services", "Financial Services"],
  ["Fitness", "Health Care"],
  ["Fleet Management", "Transportation"],
  ["Food Delivery", "Food and Beverage"],
  ["Food Processing", "Food and Beverage"],
  ["Food and Beverage", "Food and Beverage"],
  ["Forestry", "Natural Resources"],
  ["Fossil Fuels", "Energy"],
  ["Franchise", "Commerce and Shopping"],
  ["Fraud Detection", "Privacy and Security"],
  ["Freelance", "Professional Services"],
  ["Freight Service", "Transportation"],
  ["Fuel Cell", "Energy"],
  ["Funding Platform", "Lending and Investments"],
  ["Furniture", "Consumer Goods"],
  ["Gambling", "Gaming"],
  ["Gamification", "Gaming"],
  ["Gaming", "Gaming"],
  ["Genetic Testing", "Biotechnology"],
  ["Genetics", "Biotechnology"],
  ["Geothermal Energy", "Energy"],
  ["Gift Card", "Commerce and Shopping"],
  ["GPS", "Navigation and Mapping"],
  ["Graphic Design", "Design"],
  ["Green Building", "Sustainability"],
  ["GreenTech", "Sustainability"],
  ["Grocery", "Food and Beverage"],
  ["Hardware", "Hardware"],
  ["Health Care", "Health Care"],
  ["Health Diagnostics", "Health Care"],
  ["Health Insurance", "Financial Services"],
  ["Higher Education", "Education"],
  ["Home Decor", "Consumer Goods"],
  ["Home Health Care", "Health Care"],
  ["Home Improvement", "Real Estate"],
  ["Home Services", "Administrative Services"],
  ["Hospital", "Health Care"],
  ["Hospitality", "Travel and Tourism"],
  ["Hotel", "Travel and Tourism"],
  ["Human Resources", "Professional Services"],
  ["HVAC", "Manufacturing"],
  ["Hydroponics", "Agriculture and Farming"],
  ["Identity Management", "Privacy and Security"],
  ["Image Recognition", "Artificial Intelligence"],
  ["Impact Investing", "Lending and Investments"],
  ["Incubators", "Lending and Investments"],
  ["Indoor Positioning", "Navigation and Mapping"],
  ["Industrial", "Manufacturing"],
  ["Industrial Automation", "Manufacturing"],
  ["Industrial Engineering", "Science and Engineering"],
  ["Industrial Manufacturing", "Manufacturing"],
  ["Information Services", "Information Technology"],
  ["Information Technology", "Information Technology"],
  ["Infrastructure", "Information Technology"],
  ["Innovation Management", "Professional Services"],
  ["Insurance", "Financial Services"],
  ["Intellectual Property", "Professional Services"],
  ["Intelligent Systems", "Artificial Intelligence"],
  ["Interior Design", "Design"],
  ["Internet", "Internet Services"],
  ["Internet of Things", "Internet Services"],
  ["Internet Radio", "Music and Audio"],
  ["Inventory Management", "Software"],
  ["IT Infrastructure", "Information Technology"],
  ["IT Management", "Information Technology"],
  ["Jewelry", "Consumer Goods"],
  ["Journalism", "Content and Publishing"],
  ["Knowledge Management", "Software"],
  ["Language Learning", "Education"],
  ["Last Mile Transportation", "Transportation"],
  ["Law Enforcement", "Government and Military"],
  ["Lead Generation", "Sales and Marketing"],
  ["Lead Management", "Sales and Marketing"],
  ["Legal", "Professional Services"],
  ["Legal Tech", "Professional Services"],
  ["Leisure", "Community and Lifestyle"],
  ["Lending", "Lending and Investments"],
  ["Life Insurance", "Financial Services"],
  ["Life Science", "Biotechnology"],
  ["Lifestyle", "Community and Lifestyle"],
  ["Lighting", "Hardware"],
  ["Linux", "Software"],
  ["Local Advertising", "Advertising"],
  ["Local Business", "Commerce and Shopping"],
  ["Location Based Services", "Navigation and Mapping"],
  ["Logistics", "Transportation"],
  ["Loyalty Programs", "Sales and Marketing"],
  ["Machine Learning", "Artificial Intelligence"],
  ["Management Consulting", "Professional Services"],
  ["Manufacturing", "Manufacturing"],
  ["Mapping Services", "Navigation and Mapping"],
  ["Marine Transportation", "Transportation"],
  ["Market Research", "Sales and Marketing"],
  ["Marketing", "Sales and Marketing"],
  ["Marketing Automation", "Sales and Marketing"],
  ["Marketplace", "Commerce and Shopping"],
  ["Mechanical Engineering", "Science and Engineering"],
  ["Media and Entertainment", "Media and Entertainment"],
  ["Medical", "Health Care"],
  ["Medical Device", "Health Care"],
  ["Messaging", "Messaging and Telecommunications"],
  ["mHealth", "Health Care"],
  ["Micro Lending", "Lending and Investments"],
  ["Military", "Government and Military"],
  ["Mining", "Natural Resources"],
  ["Mining Technology", "Natural Resources"],
  ["Mobile", "Mobile"],
  ["Mobile Advertising", "Advertising"],
  ["Mobile Apps", "Apps"],
  ["Mobile Devices", "Mobile"],
  ["Mobile Payments", "Payments"],
  ["MOOC", "Education"],
  ["Music", "Music and Audio"],
  ["Music Education", "Education"],
  ["Music Streaming", "Music and Audio"],
  ["Nanotechnology", "Science and Engineering"],
  ["Native Advertising", "Advertising"],
  ["Natural Language Processing", "Artificial Intelligence"],
  ["Natural Resources", "Natural Resources"],
  ["Navigation", "Navigation and Mapping"],
  ["Network Hardware", "Hardware"],
  ["Network Security", "Privacy and Security"],
  ["News", "Content and Publishing"],
  ["NFC", "Payments"],
  ["Non Profit", "Community and Lifestyle"],
  ["Nuclear", "Energy"],
  ["Nutrition", "Health Care"],
  ["Office Administration", "Administrative Services"],
  ["Oil and Gas", "Energy"],
  ["Online Forums", "Internet Services"],
  ["Online Games", "Gaming"],
  ["Online Portals", "Internet Services"],
  ["Open Source", "Software"],
  ["Operating Systems", "Software"],
  ["Organic Food", "Food and Beverage"],
  ["Outdoor Advertising", "Advertising"],
  ["Outsourcing", "Professional Services"],
  ["P2P Money Transfer", "Payments"],
  ["Packaging Services", "Manufacturing"],
  ["Paper Manufacturing", "Manufacturing"],
  ["Parking", "Transportation"],
  ["Payments", "Payments"],
  ["PC Games", "Gaming"],
  ["Peer to Peer", "Internet Services"],
  ["Personal Finance", "Financial Services"],
  ["Personal Health", "Health Care"],
  ["Personalization", "Software"],
  ["Pet", "Consumer Goods"],
  ["Pharmaceutical", "Biotechnology"],
  ["Photo Sharing", "Content and Publishing"],
  ["Photography", "Content and Publishing"],
  ["Physical Security", "Privacy and Security"],
  ["Plant-Based Foods", "Food and Beverage"],
  ["Podcast", "Music and Audio"],
  ["Point of Sale", "Payments"],
  ["Politics", "Government and Military"],
  ["Ports and Harbors", "Transportation"],
  ["Precious Metals", "Natural Resources"],
  ["Predictive Analytics", "Data and Analytics"],
  ["Presentations", "Software"],
  ["Price Comparison", "Commerce and Shopping"],
  ["Primary Education", "Education"],
  ["Printing", "Manufacturing"],
  ["Privacy", "Privacy and Security"],
  ["Private Cloud", "Information Technology"],
  ["Procurement", "Professional Services"],
  ["Product Design", "Design"],
  ["Product Management", "Software"],
  ["Product Research", "Science and Engineering"],
  ["Productivity Tools", "Software"],
  ["Professional Networking", "Internet Services"],
  ["Professional Services", "Professional Services"],
  ["Project Management", "Software"],
  ["Property Development", "Real Estate"],
  ["Property Insurance", "Financial Services"],
  ["Property Management", "Real Estate"],
  ["Public Relations", "Sales and Marketing"],
  ["Public Safety", "Government and Military"],
  ["Public Transportation", "Transportation"],
  ["Publishing", "Content and Publishing"],
  ["Quality Assurance", "Software"],
  ["Quantum Computing", "Science and Engineering"],
  ["Railroad", "Transportation"],
  ["Real Estate", "Real Estate"],
  ["Real Estate Investment", "Real Estate"],
  ["Recipe", "Food and Beverage"],
  ["Recreation", "Sports"],
  ["Recruiting", "Professional Services"],
  ["Recycling", "Sustainability"],
  ["Renewable Energy", "Energy"],
  ["Rental", "Real Estate"],
  ["Reputation", "Sales and Marketing"],
  ["Reservations", "Travel and Tourism"],
  ["Residential", "Real Estate"],
  ["Resorts", "Travel and Tourism"],
  ["Restaurants", "Food and Beverage"],
  ["Retail", "Commerce and Shopping"],
  ["Retail Technology", "Commerce and Shopping"],
  ["RFID", "Hardware"],
  ["Ride Sharing", "Transportation"],
  ["Risk Management", "Financial Services"],
  ["Robotics", "Hardware"],
  ["RPA", "Software"],
  ["SaaS", "Software"],
  ["Sales", "Sales and Marketing"],
  ["Sales Automation", "Sales and Marketing"],
  ["Same Day Delivery", "Transportation"],
  ["Satellites", "Hardware"],
  ["Scheduling", "Software"],
  ["Search Engine", "Internet Services"],
  ["Secondary Education", "Education"],
  ["Security", "Privacy and Security"],
  ["SEM", "Sales and Marketing"],
  ["Semiconductor", "Hardware"],
  ["SEO", "Sales and Marketing"],
  ["Serious Games", "Gaming"],
  ["Service Industry", "Professional Services"],
  ["Sharing Economy", "Internet Services"],
  ["Shipping", "Transportation"],
  ["Shopping", "Commerce and Shopping"],
  ["Simulation", "Software"],
  ["Skill Assessment", "Education"],
  ["Small and Medium Businesses", "Software"],
  ["Smart Building", "Real Estate"],
  ["Smart Cities", "Government and Military"],
  ["Smart Home", "Consumer Electronics"],
  ["SMS", "Messaging and Telecommunications"],
  ["Snack Food", "Food and Beverage"],
  ["Social", "Community and Lifestyle"],
  ["Social Entrepreneurship", "Community and Lifestyle"],
  ["Social Impact", "Community and Lifestyle"],
  ["Social Media", "Internet Services"],
  ["Social Media Advertising", "Advertising"],
  ["Social Media Management", "Sales and Marketing"],
  ["Social Network", "Internet Services"],
  ["Social Recruiting", "Professional Services"],
  ["Software", "Software"],
  ["Software Engineering", "Software"],
  ["Solar", "Energy"],
  ["Space Travel", "Science and Engineering"],
  ["Speech Recognition", "Artificial Intelligence"],
  ["Sporting Goods", "Sports"],
  ["Sports", "Sports"],
  ["Staffing Agency", "Professional Services"],
  ["Stock Exchanges", "Financial Services"],
  ["Subscription Service", "Commerce and Shopping"],
  ["Supply Chain Management", "Transportation"],
  ["Sustainability", "Sustainability"],
  ["Synthetic Biology", "Biotechnology"],
  ["Technical Support", "Information Technology"],
  ["Telecommunications", "Messaging and Telecommunications"],
  ["Television", "Video"],
  ["Test and Measurement", "Science and Engineering"],
  ["Text Analytics", "Data and Analytics"],
  ["Therapeutics", "Biotechnology"],
  ["Ticketing", "Events"],
  ["Tour Operator", "Travel and Tourism"],
  ["Tourism", "Travel and Tourism"],
  ["Toys", "Consumer Goods"],
  ["Trading Platform", "Financial Services"],
  ["Training", "Education"],
  ["Transaction Processing", "Payments"],
  ["Translation Service", "Professional Services"],
  ["Transportation", "Transportation"],
  ["Travel", "Travel and Tourism"],
  ["Travel Accommodations", "Travel and Tourism"],
  ["Travel Agency", "Travel and Tourism"],
  ["Trucking", "Transportation"],
  ["Tutoring", "Education"],
  ["Unified Communications", "Messaging and Telecommunications"],
  ["Universities", "Education"],
  ["Usability Testing", "Design"],
  ["UX Design", "Design"],
  ["Vacation Rental", "Travel and Tourism"],
  ["Venture Capital", "Lending and Investments"],
  ["Video", "Video"],
  ["Video Advertising", "Advertising"],
  ["Video Chat", "Messaging and Telecommunications"],
  ["Video Conferencing", "Messaging and Telecommunications"],
  ["Video Editing", "Video"],
  ["Video Games", "Gaming"],
  ["Video on Demand", "Video"],
  ["Video Streaming", "Video"],
  ["Virtual Assistant", "Artificial Intelligence"],
  ["Virtual Currency", "Financial Services"],
  ["Virtual Reality", "Hardware"],
  ["Virtualization", "Information Technology"],
  ["VoIP", "Messaging and Telecommunications"],
  ["Warehousing", "Transportation"],
  ["Waste Management", "Sustainability"],
  ["Water", "Natural Resources"],
  ["Water Purification", "Sustainability"],
  ["Wealth Management", "Financial Services"],
  ["Wearables", "Consumer Electronics"],
  ["Web Apps", "Software"],
  ["Web Browsers", "Internet Services"],
  ["Web Design", "Design"],
  ["Web Development", "Software"],
  ["Web Hosting", "Internet Services"],
  ["Wedding", "Community and Lifestyle"],
  ["Wellness", "Health Care"],
  ["Wholesale", "Commerce and Shopping"],
  ["Wind Energy", "Energy"],
  ["Wine And Spirits", "Food and Beverage"],
  ["Wireless", "Messaging and Telecommunications"],
  ["Young Adults", "Community and Lifestyle"],
];

const GROUP_ITEMS: CrunchbaseIndustry[] = CRUNCHBASE_INDUSTRY_GROUPS.map(name => ({
  name,
  group: "Industry group",
}));

const SPECIFIC_ITEMS: CrunchbaseIndustry[] = CRUNCHBASE_INDUSTRY_ROWS.map(([name, group]) => ({ name, group }));

const BY_NAME = new Map<string, CrunchbaseIndustry>();
for (const item of [...GROUP_ITEMS, ...SPECIFIC_ITEMS]) {
  if (!BY_NAME.has(item.name.toLowerCase())) BY_NAME.set(item.name.toLowerCase(), item);
}

export const CRUNCHBASE_INDUSTRIES: CrunchbaseIndustry[] = [...BY_NAME.values()];

export function searchCrunchbaseIndustries(
  query: string,
  selected: readonly string[] = [],
  limit = 12,
): CrunchbaseIndustry[] {
  const taken = new Set(selected.map(name => name.toLowerCase()));
  const q = query.trim().toLowerCase();
  const pool = q
    ? CRUNCHBASE_INDUSTRIES
    : GROUP_ITEMS;
  const ranked = pool
    .filter(item => !taken.has(item.name.toLowerCase()))
    .map(item => {
      const name = item.name.toLowerCase();
      const group = item.group.toLowerCase();
      if (!q) return { item, score: 0 };
      if (name === q) return { item, score: 0 };
      if (name.startsWith(q)) return { item, score: 1 };
      if (name.includes(q)) return { item, score: 2 };
      if (group.startsWith(q) || group.includes(q)) return { item, score: 3 };
      return null;
    })
    .filter((row): row is { item: CrunchbaseIndustry; score: number } => Boolean(row))
    .sort((left, right) => left.score - right.score || left.item.name.localeCompare(right.item.name));
  return ranked.slice(0, limit).map(row => row.item);
}
